name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy locally
        run: |
          echo "Starting deployment..."
          mkdir -p /home/caio/myproject
          cd /home/caio/myproject

          # Pull latest changes
          if [ -d ".git" ]; then
            git reset --hard
            git clean -fd
            git pull origin main
          else
            git clone https://github.com/hrik01/testcicd.git .
          fi

          # Copy files to web server directory
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          echo "Deployment completed!"
